# These values are auto-populated during the build process
endpointVersion: ""
clusterProjectID: ""

# Once the Application Project has been created via Terraform, set that project id here.
# This is used to specify the GCP service account to use with Workload Identity in service_account.yaml.
appProjectID: ""

endpointServiceName: dashboard-dev

configMapVars:
  APP_DEBUG: "true"
  APP_ENV: dev

cloudsql:
  instances:
    [] # the cloudsql proxy can proxy multiple instances at once on different ports. Pass an array containing the instance
    # - connectionName: "project:us-central1:instance" #this is the connection name for the instance
    #   port: 3306

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-cluster-issuer
  rules:
    - host: -com.dev.gcp.com
      path: /dashboard/loans
      svc: dashboard
      port: 80
  tls:
    - secretName: dashboard-tls
      hosts:
        - -com.dev.gcp.com

react:
  app:
    dashboardApi:
      url: https://dashboard-api.dev.gcp.com
    auth0:
      domain: login-dev.gcp.com
      audience: auth.dev.gcp.com
      clientId: GQErS1nMmM571eqHu7FndwQWo7FEZyQU